resolver: lts-3.10

packages:
- '.'
- location:
    git: https://github.com/dbp/groundhog-postgres-snap
    commit: 05f2ab84db8e68cc5f4d3d03b86571348e55c962
  extra-dep: true
- location:
    git: https://github.com/dbp/groundhog-utils
    commit: 29fb9d90aeda85bf5b9126a36b1448f9d4af50b1
  extra-dep: true
- location:
    git: https://github.com/dbp/restful-snap
    commit: 5f5e91dc7ce0e5e624a61998ede71e211262f26e
  extra-dep: true

extra-deps:
- digestive-functors-heist-0.8.6.2
- digestive-functors-snap-0.6.1.3
- restful-snap-0.2
- snap-extras-0.11.0.2
- snap-loader-static-0.9.0.2
- readable-0.3.1
